### ISSUE TITLE
Bug in bilinear sampler of transformer

### ISSUE THREAD

**Issue by marissaweis** [kevinzakka/spatial_transformer_network#13]
Hi,
I tried the spatial transformer with a simple toy image and identity transform to verify that it works correctly, but I think that it has a bug, unless I'm doing something wrong.

This is the input image I used:
![original_toy_example](https://user-images.githubusercontent.com/32958388/39761608-d4f58c48-52d8-11e8-8e5b-01641c72e033.png)

When I transform it with theta=[[1,0,0,0,1,0]], I get this as an output, which is clearly not identical to the input:
![identity_transform](https://user-images.githubusercontent.com/32958388/39761700-0d268c98-52d9-11e8-92a3-1481c6e97e66.png)

I fixed it by adjusting the grid range in the bilinear sampler by -1 and shifting the calculation of the deltas before the clipping operation. Here is the fixed code:

```
def bilinear_sampler(img, x, y):
        """
        Performs bilinear sampling of the input images according to the 
        normalized coordinates provided by the sampling grid. Note that 
        the sampling is done identically for each channel of the input.
        To test if the function works properly, output image should be
        identical to input image when theta is initialized to identity
        transform.
        Input
        -----
        - img: batch of images in (B, H, W, C) layout.
        - grid: x, y which is the output of affine_grid_generator.
        Returns
        -------
        - interpolated images according to grids. Same size as grid.
        """
        # prepare useful params
        B = tf.shape(img)[0]
        H = tf.shape(img)[1]
        W = tf.shape(img)[2]
        C = tf.shape(img)[3]

        max_y = tf.cast(H - 1, 'int32')
        max_x = tf.cast(W - 1, 'int32')
        zero = tf.zeros([], dtype='int32')

        # cast indices as float32 (for rescaling)
        x = tf.cast(x, 'float32')
        y = tf.cast(y, 'float32')

        # rescale x and y to [0, W-1/H-1]
        x = 0.5 * ((x + 1.0) * tf.cast(max_x, 'float32'))
        y = 0.5 * ((y + 1.0) * tf.cast(max_y, 'float32'))

        # grab 4 nearest corner points for each (x_i, y_i)
        # i.e. we need a rectangle around the point of interest
        x0 = tf.floor(x)
        x1 = x0 + 1
        y0 = tf.floor(y)
        y1 = y0 + 1

        # calculate deltas
        wa = (x1-x) * (y1-y)
        wb = (x1-x) * (y-y0)
        wc = (x-x0) * (y1-y)
        wd = (x-x0) * (y-y0)

        #recast as int for index calculation
        x0 = tf.cast(x0, 'int32')
        x1 = tf.cast(x1, 'int32')
        y0 = tf.cast(y0, 'int32')
        y1 = tf.cast(y1, 'int32')

        # clip to range [0, H/W] to not violate img boundaries
        x0 = tf.clip_by_value(x0, zero, max_x)
        x1 = tf.clip_by_value(x1, zero, max_x)
        y0 = tf.clip_by_value(y0, zero, max_y)
        y1 = tf.clip_by_value(y1, zero, max_y)

        # get pixel value at corner coords
        Ia = get_pixel_value(img, x0, y0)
        Ib = get_pixel_value(img, x0, y1)
        Ic = get_pixel_value(img, x1, y0)
        Id = get_pixel_value(img, x1, y1)

        # add dimension for addition
        wa = tf.expand_dims(wa, axis=3)
        wb = tf.expand_dims(wb, axis=3)
        wc = tf.expand_dims(wc, axis=3)
        wd = tf.expand_dims(wd, axis=3)

        # compute output
        out = tf.add_n([wa*Ia, wb*Ib, wc*Ic, wd*Id])

        return out
```

With this code I recover the original image by transformation with the identity matrix.

**Comment by kevinzakka** [comment]
@marissaweis Wow, so I was testing my bilinear sampler on a cat image (you can see it in SanityCheck.ipynb) and it looked alright when I used the identity transform. However, on closer inspection, it seems there are some black pixels at the bottom right corner of the image which were not present initially so there definitely is an error in the code.

**Comment by marissaweis** [comment]
The black pixels seem to emerge due to the calculation of the deltas after clipping. If I only fix the range, i.e. substitute H with max_x in `x = 0.5 * ((x + 1.0) * tf.cast(max_x, 'float32'))` I get the following:

![identity_transform_fixed_range](https://user-images.githubusercontent.com/32958388/39764145-4484e012-52df-11e8-81f8-5f0f7fac1343.png)

**Comment by kevinzakka** [comment]
@marissaweis I'm not sure your fix is totally correct. If I try a 45 degree rotation, I get some weird reflection effect. Here's an example on the cat image:

![screen shot 2018-06-02 at 8 19 57 pm](https://user-images.githubusercontent.com/10518920/40879844-61be1ef8-66af-11e8-855c-c28cafdf3fe2.png)

And here's the result of my current implementation:

![screen shot 2018-06-02 at 8 18 52 pm](https://user-images.githubusercontent.com/10518920/40879848-6ab5b0de-66af-11e8-8cee-a837095ce310.png)

**Comment by kevinzakka** [comment]
@marissaweis I think I've fixed the error. Could you try the updated code with your test input?

**Comment by marissaweis** [comment]
I used my fix in quite a different setting and never tried rotation. Thanks for catching that! I think the problem is, that I put the computations of the deltas before the clipping to avoid the corner case on the right and lower image edge where they were all set to zero, but with rotation you need of course some kind of clipping to determine when you are out of the image bounds.

**Comment by marissaweis** [comment]
I tried your updated code with the toy example posted above. Unfortunatly, there still seems to be something strange happening. I get the following:

![test_new](https://user-images.githubusercontent.com/32958388/40884431-c854c130-6713-11e8-92f7-864aabfacbca.png)

**Comment by kevinzakka** [comment]
@marissaweis could you provide me with the code to generate that test input? I'd like to debug with it. Thanks

**Comment by marissaweis** [comment]
```
s = 5

a = np.ones((s,s))
b = np.zeros((s,s))
c = np.array([[0.25]*s]*s)
d = np.array([[0.75]*s]*s)

ab = np.concatenate([a,b])
cd = np.concatenate([c,d])

test = np.concatenate([ab,cd], axis=1)

test = np.pad(test, (1,1), mode='constant', constant_values=(4,4))
```

**Comment by kevinzakka** [comment]
@marissaweis So if you increase s to `s=20`, and run it with my code, the identity transform works, but the rotation does some weird edge blurring. I think this is expected because bilinear interpolation can work differently with edge pixels depending on the implementation. 

Here's a picture of the identity:

![download](https://user-images.githubusercontent.com/10518920/40884891-dd5f81f8-6724-11e8-816b-dd371384c8f6.png)

And the rotation:

![download-1](https://user-images.githubusercontent.com/10518920/40884892-e1c0fe8e-6724-11e8-826e-b63681a5a0b0.png)

In any case, I think just the edges are getting affected and with RGB images, there's no noticeable difference. Small bugs like these tend to regularize DNNs so I don't think we should worry too much about it.

**Comment by marissaweis** [comment]
Is it the same code that you have online? Because I get this with s=20:

![test2](https://user-images.githubusercontent.com/32958388/40885168-831ca7d2-6721-11e8-8626-31a92ef40cd6.png)

But maybe I have a bug somehwere else. Identity theta is theta=[[1,0,0,0,1,0]], right?

**Comment by kevinzakka** [comment]
@marissaweis my bad, just revert `max_h - 1` to `max_h` and `max_w - 1` to `max_w`.

**Comment by zachluo** [comment]
@marissaweis @kevinzakka so the answer is we should use this code 
x = 0.5 * ((x + 1.0) * tf.cast(max_x, 'float32'))
y = 0.5 * ((y + 1.0) * tf.cast(max_y, 'float32'))
rather than max_x - 1 and max_y - 1, right?

**Comment by kevinzakka** [comment]
@zachluo It really doesn't matter to be honest. At the level of the network, it will just end up acting as a regularizer.
