### ISSUE TITLE
STN implementation in tensorflow

### ISSUE THREAD

**Issue by zachluo** [kevinzakka/spatial_transformer_network#19]
Does anyone find something wrong that tf.gather or tf.gather_nd will not be differential w.t. coordinates, which used in STN? In addition, TF officially implement an op namely, tf.contrib.resampler.resampler that is totally differential.

**Comment by kevinzakka** [comment]
@zachluo tf.gather is basically a matrix multiplication with 1s and 0s where 1 means select and 0 means don't. In that sense, it is differentiable.

**Comment by zachluo** [comment]
@kevinzakka When I use something like tf.gradients(tf.gather(data, index), index), it returns [None]. Of course, tf.gradients(tf.gather(data, index), data) will return gradients.

**Comment by zachluo** [comment]
@kevinzakka Instead, tf.contrib.resampler.resampler can return gradients for data and index

**Comment by kevinzakka** [comment]
@zachluo i’ll take a look these next 2 days!

**Comment by zachluo** [comment]
@kevinzakka Hi, I found the declaration of tf.gradients (https://www.tensorflow.org/api_docs/python/tf/gradients). It says that All integer tensors are considered constant with respect to all xs, as if they were included in stop_gradients. And coordinates in tf.gather must be int32 or int64, which means it can not be bp.
