### ISSUE TITLE
Request to add a license?

### ISSUE THREAD

**Issue by MarxSoul55** [kevinzakka/spatial_transformer_network#4]
Hello there,

I've gone through your blog-posts on spatial-transformer networks, and they're very informative! I would like to have these networks for myself, but I don't want to reinvent the wheel—I would simply use your implementation, but your repository doesn't list a license, so I hesitate to do so. Therefore, I kindly request that you add a `LICENSE.txt`.

If you are inclined to do so, please see [this website](https://choosealicense.com/) for some informal guidance on common open-source licenses.

**Comment by kevinzakka** [comment]
MIT license added, thanks for pointing it out!
